### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedark.nvim#2]
## Dark

![Screen Shot 2021-08-30 at 18 53 56](https://user-images.githubusercontent.com/9512444/131382995-d2378741-954e-4f03-9b73-b514be3d4464.png)

## Light

![Screen Shot 2021-08-30 at 18 57 17](https://user-images.githubusercontent.com/9512444/131383409-e4686a46-8943-4e73-af57-14bba8863512.png)

**Comment by olimorris** [comment]
# Color references

## Dark
![dark_colors](https://user-images.githubusercontent.com/9512444/136249668-0939e37e-23e4-48a3-af1d-44fc7190e12e.png)

## Light
![light_colors](https://user-images.githubusercontent.com/9512444/136249706-990609bd-3404-4bbb-ae37-77de437f28dd.png)

**Comment by olimorris** [comment]
# After theme upgrade
After shifting the schemes closer to `One Dark Pro` in VS Code, we now have new screenshots.

## Dark - Python
![Screen Shot 2021-10-15 at 22 41 25@2x](https://user-images.githubusercontent.com/9512444/137556870-ee47b2ea-b9e2-4b56-8d82-2e99da249af4.png)

### Comparison to VS Code
![Screen Shot 2021-10-15 at 22 47 24@2x](https://user-images.githubusercontent.com/9512444/137557243-d30fc6c7-137d-47c8-a52b-5993a718289f.png)

## Dark - React
![Screen Shot 2021-10-15 at 22 37 40@2x](https://user-images.githubusercontent.com/9512444/137556833-f45452ff-e63b-421c-bf73-e867207972ed.png)

## Light - Python
![Screen Shot 2021-10-15 at 22 41 54@2x](https://user-images.githubusercontent.com/9512444/137556929-77ddb821-53fc-4bd7-a5dc-f0c67729249b.png)

## Light - React
![Screen Shot 2021-10-15 at 22 39 07@2x](https://user-images.githubusercontent.com/9512444/137556949-0829b6e3-d1f6-453d-b225-1aae1d1ccfe0.png)

**Comment by olimorris** [comment]
# Lualine

## Dark
<img width="1509" alt="Screen Shot 2021-11-16 at 09 23 46@2x" src="https://user-images.githubusercontent.com/9512444/141958202-77a8e021-d396-496d-87bf-2803bade6717.png">

## Light
<img width="1510" alt="Screen Shot 2021-11-16 at 09 24 16@2x" src="https://user-images.githubusercontent.com/9512444/141958282-b1ce4e97-a1a3-4d99-acc1-74ca510f7296.png">

**Comment by cwj092** [comment]
Hi, thanks for creating this theme. May I know if there is a place to find the config to make it looks exactly like the screenshot in OneLight above? I tried to play around with the config but still unable to make it looks the same, especially the bottom bar (lualine?)

**Comment by olimorris** [comment]
@cwj092 for the pics I just made my feline statusbar a block of color. You can see my dotfiles for how I set feline up and I believe I just set the background color to be the mode color.

**Comment by cwj092** [comment]
Thanks @olimorris, I'm able to setup now, your dotfiles is GOLD :)

**Comment by olimorris** [comment]
## Treesitter Playground Output

<img width="767" alt="Screen Shot 2022-10-19 at 08 51 22@2x" src="https://user-images.githubusercontent.com/9512444/196629898-ce690157-99f5-4540-bdfa-e28ac3d5e012.png">

**Comment by olimorris** [comment]
## Semantic Tokens

![Semantic Highlights](https://user-images.githubusercontent.com/9512444/211270743-98db1a1c-43c7-4a2d-b231-de18d9385eff.png)

**Comment by olimorris** [comment]
## Languages

### Python

![2024-02-10 23_01_46 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/d390a8c6-8d0a-46f3-bb60-babc52880b00)

### JavaScript

![2024-02-10 22_58_36 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/ef1ee31e-5176-4345-8e0f-6c13883e7a9b)

### TypeScript

![2024-02-10 22_59_33 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/c9faca03-5949-4ccf-bc68-72b05de9c363)

### Rust

![2024-02-10 23_01_01 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/0a9f8802-5de8-4750-912d-25215e23e2b3)

### Go

![2024-02-10 23_00_25 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/0dd5b6f2-4d7f-4c97-87c2-74e94f7f06a7)

### PHP

![2024-02-10 22_58_15 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/89f26911-1c23-4ee0-8e69-1aaceaf2c5db)

### Ruby

![2024-02-10 22_59_06 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/b4334c38-2464-4502-ab55-10cbd9832e19)

### Java

![2024-02-10 23_02_10 - WezTerm@2x](https://github.com/olimorris/onedarkpro.nvim/assets/9512444/09556103-b63d-4472-aeb0-03101a1d9879)

**Comment by olimorris** [comment]
![Image](https://github.com/user-attachments/assets/37df30fa-e79d-44d2-af58-91d15152856c)
