### ISSUE TITLE
vim command window the font color is hard to distinguish

### ISSUE THREAD

**Issue by leiwang-ninjia** [olimorris/onedark.nvim#3]
![image](https://user-images.githubusercontent.com/8272638/131808083-912b3589-3c81-4c6c-b726-78f778572841.png)

**Comment by davidvalaz** [comment]
If you're using the new version of `onedark.nvim`, I'd recommend applying this to your config:

```lua
hlgroups = {
    ModeMsg = {'Normal'}
}
```

This will set the msg part of vim/neovim to have the default background and foreground colors

**Comment by olimorris** [comment]
If you're using the new version of `onedark.nvim`, I'd recommend applying this to your config:

```lua
hlgroups = {
    ModeMsg = {'Normal'}
}
```

This will set the msg part of vim/neovim to have the default background and foreground colors

**Comment by olimorris** [comment]
I'll leave this issue open for a while and if we get enough upvotes/comments will gladly do so.

**Comment by olimorris** [comment]
@leiwang-ninjia - FYI this is now the default in the theme
